language: c

env:
  global:
    - LANG="zh_CN.UTF-8"
    - TMUX_VERSION=2.9a
    - UTF8PROC_VERSION=2.4.0
    - LIBEVENT_VERSION=2.1.10-stable
    - NCURSES_VERSION=6.1
    - CMAKE_PREFIX=$HOME/prebuilt/cmake ;
    - CMAKE_LINUX_URL=https://github.com/Kitware/CMake/releases/download/v3.14.5/cmake-3.14.5-Linux-x86_64.sh ;

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      env: CC=musl-gcc CXX=musl-gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - musl
            - musl-dev
            - musl-tools
            - libtinfo-dev
    
install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then

          if [ ! -e "$CMAKE_BIN" ]; then

            mkdir -p "$CMAKE_PREFIX";

            curl --insecure -L "$CMAKE_LINUX_URL" -o cmake-linux.sh ;

            bash cmake-linux.sh --skip-license --prefix=$CMAKE_PREFIX ;

          fi

      fi

script: 
    - export PATH=$CMAKE_PREFIX:$PATH ;
    - if [ -e prebuilt ]; then rm -rf prebuilt; fi
    - chmod +x ./build-tmux.sh ;
    - ./build-tmux.sh ;

cache:
  apt: true
  directories:
  - $CMAKE_PREFIX

notifications:
  email: false
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"

deploy:
  provider: releases
  api_key:
    secure: gCMMEsuAMqbZmDmcWq4A+NYZ4s7NPNlzrqLFbz0G0QHR05QVklQBh0MRrxi9NLq6mmbYJgxm4VYkQVZfyA5aG0vUNd91As1KVOcGZ/sRZCjMkZVNgkzT9vs1cAyG4/hXvwa/Odu0JNqV6pTfBsMCX46Nut/UkoCY8Au+s1ix2jGeeRO38spyixwjnsT0r9/mzlLs+4s0voowjiRNWjUOlJdpOBNXkG7KKk0M8uIe3EnDWsVZEHsbLbhhbh9/sCtj6bgAFXM0iPZtT+DVUlmqs2v8uapVGUVA+4O9tTVz9zE1rTNen3CravVqXV+tz4mcu958h0p31qtmdFKcC+94dATqQUcvXY9JVeMmCWHQ84Nl7oIX4sxB08qS6FnQMqXVovZPf1GdB6oi0S5vHy1w+df2tBLLLNAYOXerE8eO9/bqy7f2s1DpDXlyJ6sRt6o1dpga+PMfPe+yB9ev1kQBt2ISSAtz1N7Ix0GkXXWYDWm5lys13oRc0KmwYc4KwF1HeZA0SEiCziwAcpbxLt4jTGW9uPwW24+h12rDDLOfqLWb+JCW5COWoWjCAPp7+zggnnRzHVW+aSJsvyQY76HQ2qFjmPCfe8FwsoPPqcY8gswyzC4Ho3DUSAWZEKLmU98KUbjCAYtp4R+NwTKnvbffhPu831dcLD2zGgLLlLT86hA=
  file_glob: true
  file: "*.musl-bin.tar.*"
  skip_cleanup: true
  overwrite: true
  draft: true
  on:
    all_branches: true
    tags: true
